 
ME_Processing_Resource Me_Regular_Processor leon3 Proc_Res_Canvas 360 40 
ME_Timer Me_System_Timer leon3 Proc_Res_Canvas 200 40 
ME_Scheduler Me_Primary_Scheduler rtms Proc_Res_Canvas 40 40 
ME_Scheduler Me_Primary_Scheduler rtms Sched_Server_Canvas 200 125 
ME_Scheduling_Server Me_Server tcmanager Sched_Server_Canvas 114 287 
ME_Scheduling_Server Me_Server hk_fdirmng Sched_Server_Canvas 17 171 
ME_Scheduling_Server Me_Server bkgtcexec Sched_Server_Canvas 13 77 
ME_Scheduling_Server Me_Server irq18bottomhalftask Sched_Server_Canvas 295 287 
ME_Scheduling_Server Me_Server irq18handler Sched_Server_Canvas 425 77 
ME_Scheduling_Server Me_Server obsmnger Sched_Server_Canvas 425 168 
ME_Shared_Resource Me_Priority_Inheritance_Resource sc_channeltx Shared_Res_Canvas 40 40 
ME_Operation Me_Simple_Operation irq18tophalf Operation_Canvas 38 124 
ME_Operation Me_Simple_Operation irq18bottomhalf Operation_Canvas 43 37 
ME_Operation Me_Simple_Operation fgettc Operation_Canvas 1386 206 
ME_Operation Me_Simple_Operation sc_channeltx_tm Operation_Canvas 625 196 
ME_Operation Me_Enclosing_Operation fmngtcrejection Operation_Canvas 824 57 
ME_Operation Me_Enclosing_Operation fdohk_fdir Operation_Canvas 624 57 
ME_Operation Me_Composite_Operation cop_ftc_fwd Operation_Canvas 1153 105 
ME_Operation Me_Enclosing_Operation fexectc Operation_Canvas 820 330 
ME_Operation Me_Simple_Operation ftcexecctrl Operation_Canvas 820 232 
ME_Operation Me_Simple_Operation fdo_attitudectrl Operation_Canvas 45 254 
ME_Operation Me_Simple_Operation fprog_attitudectrl Operation_Canvas 44 368 
ME_Operation Me_Composite_Operation cop_obsmng Operation_Canvas 235 318 
ME_Operation Me_Enclosing_Operation fexec_bkgtc Operation_Canvas 623 316 
ME_Operation Me_Enclosing_Operation fexec_hkfdir Operation_Canvas 452 199 
ME_Operation Me_Enclosing_Operation fmng_acceptance Operation_Canvas 817 151 
ME_Operation Me_Simple_Operation ffwd_x_tc Operation_Canvas 1384 102 
ME_Operation Me_Composite_Operation cop_prio Operation_Canvas 1153 300 
ME_Operation Me_Composite_Operation cop_reje Operation_Canvas 1152 210 
ME_Transaction Me_Regular_Transaction trans_bkgtc Transaction_Canvas 365 49 
ME_Transaction Me_Regular_Transaction trans_hk_fdir Transaction_Canvas 138 81 
ME_Transaction Me_Regular_Transaction trans_prio Transaction_Canvas 364 127 
ME_Transaction Me_Regular_Transaction trans_hk_exec Transaction_Canvas 363 204 
ME_Transaction Me_Regular_Transaction trans_attitude Transaction_Canvas 137 176 
ME_Link Me_External_Link ev_new_rejected_tc,trans_bkgtc trans_new_rejected_tc 85 55 
ME_Link Me_Internal_Link ev_irq18bottomhalf_signal,trans_bkgtc trans_new_rejected_tc 84 234 
ME_Link Me_Internal_Link ev_rxtc_edroomirqsignal,trans_bkgtc trans_new_rejected_tc 273 120 
ME_Link Me_Internal_Link dl_new_rejected_tc,trans_bkgtc trans_new_rejected_tc 473 235 
ME_Link Me_External_Link ev_hk,trans_hk_fdir trans_hk_fdir 85 55 
ME_Link Me_Internal_Link dl_ev2,trans_hk_fdir trans_hk_fdir 465 55 
ME_Link Me_Internal_Link final,trans_bkgtc trans_new_rejected_tc 652 109 
ME_Link Me_External_Link ev_prio,trans_prio trans_prio 15 26 
ME_Link Me_Internal_Link ev_irq18bottomh,trans_prio trans_prio 176 32 
ME_Link Me_Internal_Link ev_rxtc_edroom,trans_prio trans_prio 387 31 
ME_Link Me_Internal_Link dl_prio,trans_prio trans_prio 462 196 
ME_Link Me_External_Link ev_hk,trans_hk_exec trans_hk_exec 32 25 
ME_Link Me_Internal_Link ev_irq18bottomhandler,trans_hk_exec trans_hk_exec 28 196 
ME_Link Me_Internal_Link ev_rxtc_edroom,trans_hk_exec trans_hk_exec 196 104 
ME_Link Me_Internal_Link dl_hk,trans_hk_exec trans_hk_exec 382 190 
ME_Link Me_Internal_Link final,trans_hk_exec trans_hk_exec 563 105 
ME_Link Me_External_Link ev_attitude,trans_attitude trans_attitude 23 76 
ME_Link Me_Internal_Link dl_attitude,trans_attitude trans_attitude 336 75 
ME_Event_Handler Me_Simple_Event_Handler 1,trans_bkgtc trans_new_rejected_tc 64 133 
ME_Event_Handler Me_Simple_Event_Handler 2,trans_bkgtc trans_new_rejected_tc 251 217 
ME_Event_Handler Me_Simple_Event_Handler 1,trans_hk_fdir trans_hk_fdir 230 40 
ME_Event_Handler Me_Simple_Event_Handler 3,trans_bkgtc trans_new_rejected_tc 632 217 
ME_Event_Handler Me_Simple_Event_Handler 4,trans_bkgtc trans_new_rejected_tc 451 101 
ME_Event_Handler Me_Simple_Event_Handler 1,trans_prio trans_prio 17 110 
ME_Event_Handler Me_Simple_Event_Handler 2,trans_prio trans_prio 221 107 
ME_Event_Handler Me_Simple_Event_Handler 3,trans_prio trans_prio 443 105 
ME_Event_Handler Me_Simple_Event_Handler 1,trans_hk_exec trans_hk_exec 8 91 
ME_Event_Handler Me_Simple_Event_Handler 2,trans_hk_exec trans_hk_exec 176 175 
ME_Event_Handler Me_Simple_Event_Handler 3,trans_hk_exec trans_hk_exec 357 87 
ME_Event_Handler Me_Simple_Event_Handler 4,trans_hk_exec trans_hk_exec 538 169 
ME_Event_Handler Me_Simple_Event_Handler 1,trans_attitude trans_attitude 154 59 
